-- liquibase formatted sql logicalFilePath:classpath:/db/changelog/2025/1743536269043-init-purchase-approval-tables.sql 
-- changeset edgsel:IN-00-init-purchase-approval-tables

CREATE TABLE PURCHASING_PROFILE (
    ID SERIAL                   PRIMARY KEY,
    NAME                        VARCHAR(30) UNIQUE NOT NULL,
    FINANCIAL_CAPACITY_FACTOR   INTEGER NOT NULL,
    CREATED_AT                  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT                 TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE CUSTOMER (
    ID SERIAL                          PRIMARY KEY,
    PERSONAL_ID                        BIGINT UNIQUE NOT NULL,
    PURCHASING_PROFILE_ID              INTEGER NOT NULL,
    STATUS                             VARCHAR(30) NOT NULL,
    CREATED_AT                         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT                        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT FK_CUSTOMER_PURCHASING_PROFILE FOREIGN KEY (PURCHASING_PROFILE_ID) REFERENCES PURCHASING_PROFILE(ID)
);

CREATE TABLE PURCHASE (
    ID SERIAL              PRIMARY KEY,
    CUSTOMER_ID            INTEGER NOT NULL,
    AMOUNT                 DECIMAL(18,2) NOT NULL,
    MAX_APPROVED_AMOUNT    DECIMAL(18,2) NOT NULL,
    STATUS                 VARCHAR(30) NOT NULL,
    CREATED_AT             TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT            TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT FK_PURCHASE_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

CREATE INDEX IDX_CUSTOMER_PROFILE_ID ON CUSTOMER(PURCHASING_PROFILE_ID);
CREATE INDEX IDX_PURCHASE_CUSTOMER_ID ON PURCHASE(CUSTOMER_ID);

INSERT INTO PURCHASING_PROFILE (NAME, FINANCIAL_CAPACITY_FACTOR)
VALUES
    ('PROFILE_1', 50),
    ('PROFILE_2', 100),
    ('PROFILE_3', 500);

INSERT INTO CUSTOMER (PERSONAL_ID, PURCHASING_PROFILE_ID, STATUS)
VALUES
    (12345678901, 1, 'INELIGIBLE'),
    (12345678912, 1, 'ELIGIBLE'),
    (12345678923, 2, 'ELIGIBLE'),
    (12345678934, 3, 'ELIGIBLE');
